fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.14.0
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    ruby_task_helper: 'https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper.git'
    deploy_pe: 'https://github.com/jarretlavallee/puppet-deploy_pe.git'
  symlinks:
    satellite_pe_tools: "#{source_dir}"
