name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  SERVICE_URL: https://facade-main-increase-default-worker-n-threads-6f3kfepqcq-ew.a.run.app/v1/provision

jobs:
  # Spec:
  #   uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
  #   with:
  #     runs_on: "ubuntu-20.04"
  #   secrets: "inherit"

  Acceptance:
    # needs: "Spec"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Bundle Install
      run: |
        gem install bundler
        bundle install

    - name: Spec Prep
      run: |
        echo ::group::Create the fixtures directory
        bundle exec rake spec_prep
        echo ::endgroup::

    - name: Provision
      run: |
        bundle exec bolt --log-level debug --modulepath spec/fixtures/modules plan run satellite_pe_tools::test_01_provision
        FILE='spec/fixtures/litmus_inventory.yaml'
        echo INVENTORY_PATH=$FILE >> $GITHUB_ENV

    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}

    - name: Install and Configure PE
      run: |
        bundle exec bolt --tmpdir /tmp --log-level debug --modulepath spec/fixtures/modules -i $INVENTORY_PATH --no-host-key-check  plan run satellite_pe_tools::test_02_server_setup

    - name: Run provision Tests
      run: |
        bundle exec bolt --modulepath spec/fixtures/modules -i $INVENTORY_PATH plan run satellite_pe_tools::test_03_test_run

    - name: Run Integration tests
      run: |
        env
        bundle exec rake satellite_pe_tools:integration

    - name: Remove test environment
      if: always()
      continue-on-error: true
      run: |
        bundle exec rake litmus:tear_down
